### ISSUE TITLE
Mettre en place un systeme de migrations

### ISSUE THREAD

**Issue by Grivel-l** [Grivel-l/101-memes#73]

**Comment by julien-marquet** [comment]
si tu veux parler de migration dtb t'as juste a créer un script js avec des instruction mongodb dedans et a executer : mongo script.js, . Dans la PR tagsAndSearch j'ai créer un dossier db_scripts avec un fichier js pour rajouter les tags dans chaque document

**Comment by julien-marquet** [comment]
Pas besoin de système élaboré

**Comment by Grivel-l** [comment]
Ce sera pas suffisant. J'aimerai mettre en place un systeme de scripts js. A chaque fois que tu vas lancer le server, ça va check si y a des scripts qui n'ont pas été exécutés. Si il en trouve il les executent dans leur ordre de création. Par exemple pour la PR de conversion vidéo ça va permettre de convertir toutes les vidéos déjà uploadée au moment du merge. Mais aussi d'intéragir avec mongodb comme tu l'as fait dans ton script
